version: '2'
services:
  web:
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'my_dockerized_app'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - ~/pgdata:/var/lib/postgresql
