# This is used by Docker Compose to set up prefix names for Docker images,
# containers, volumes and networks. This ensures that everything is named
# consistently regardless of your folder structure.
# What Rails environment are we in?
RAILS_ENV: development

# Rails log level.
#   Accepted values: debug, info, warn, error, fatal, or unknown
LOG_LEVEL: debug

# You would typically use `rails secret` to generate a secure token. It is
# critical that you keep this value private in production.
SECRET_TOKEN: asecuretokenwouldnormallygohere

# More details about these Puma variables can be found in config/puma.rb.
# Which address should the Puma app server bind to?
BIND_ON: 0.0.0.0:3000

# Puma supports multiple threads but in development mode you'll want to use 1
# thread to ensure that you can properly debug your application.
RAILS_MAX_THREADS: 1

# Puma supports multiple workers but you should stick to 1 worker in dev mode.
WEB_CONCURRENCY: 1

# Requests that exceed 5 seconds will be terminated and dumped to a stacktrace.
# Feel free to modify this value to fit the needs of your project, but if you
# have any request that takes more than 5 seconds you probably need to re-think
# what you are doing 99.99% of the time.
REQUEST_TIMEOUT: 20

# The database name will automatically get the Rails environment appended to it
# such as: my_dockerized_app_development or my_dockerized_app_production.
DATABASE_URL: postgresql://localhost:5432/my_app?encoding=utf8&pool=5&timeout=20000


USERNAME: admin
PASSWORD: password1

EMPLOYEES: "{'9569d8a4'=> 'Ryan H', 'bd14fa3f'=> 'Steve H'}"

